[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[project]
name = "manim-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
]
